/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hash;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author josue
 */
public class Main extends javax.swing.JFrame {

    String ruta_entrada;
    String ruta_salida;
    String abs_rute;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ruta_salida = "C:\\Users\\josue\\Documents\\Criptography\\HASH\\Texts\\output.txt";
        this.abs_rute = "C:\\Users\\josue\\Documents\\Criptography\\HASH\\Texts";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Select_text = new javax.swing.JLabel();
        Select = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        See_input = new javax.swing.JButton();
        See_output = new javax.swing.JButton();
        Create_Hash = new javax.swing.JButton();
        Verify_HASH = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Nombre.setText("Josué Ruíz Hernández");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Select_text.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Select_text.setText("Select the text");
        getContentPane().add(Select_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Select.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Select.setForeground(new java.awt.Color(255, 255, 255));
        Select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        Select.setText("Select");
        Select.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        getContentPane().add(Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, 50));

        Exit.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        Exit.setText("Exit");
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 130, 50));

        See_input.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        See_input.setForeground(new java.awt.Color(255, 255, 255));
        See_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        See_input.setText("See input");
        See_input.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        See_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                See_inputActionPerformed(evt);
            }
        });
        getContentPane().add(See_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 130, 50));

        See_output.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        See_output.setForeground(new java.awt.Color(255, 255, 255));
        See_output.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        See_output.setText("See output");
        See_output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        See_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                See_outputActionPerformed(evt);
            }
        });
        getContentPane().add(See_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 50));

        Create_Hash.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Create_Hash.setForeground(new java.awt.Color(255, 255, 255));
        Create_Hash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        Create_Hash.setText("Create HASH");
        Create_Hash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Create_Hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_HashActionPerformed(evt);
            }
        });
        getContentPane().add(Create_Hash, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, 50));

        Verify_HASH.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Verify_HASH.setForeground(new java.awt.Color(255, 255, 255));
        Verify_HASH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.jpg"))); // NOI18N
        Verify_HASH.setText("Verify HASH");
        Verify_HASH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Verify_HASH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verify_HASHActionPerformed(evt);
            }
        });
        getContentPane().add(Verify_HASH, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 200, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void See_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_See_outputActionPerformed
        Archivo.mostrarArchivo(this.ruta_salida);
    }//GEN-LAST:event_See_outputActionPerformed

    private void Create_HashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_HashActionPerformed
        String sha2=null;
        String text=null;
        try {
             text = Archivo.leerArchivo(getRutaEntrada());
             System.out.println(text.length());
             sha2 = Hash.getSha(text);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        text = text + "\r\n" + sha2;
        try {
            Archivo.escribirArchivo(text, this.ruta_salida);
            JOptionPane.showMessageDialog(null,"HASH written successfully");
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Create_HashActionPerformed

    private void Verify_HASHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verify_HASHActionPerformed
        try {
            if(Hash.verifySha(getRutaEntrada())==true)
                JOptionPane.showMessageDialog(null,":)");
            else
                JOptionPane.showMessageDialog(null,":(");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Verify_HASHActionPerformed

    private void See_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_See_inputActionPerformed
        Archivo.mostrarArchivo(getRutaEntrada());
    }//GEN-LAST:event_See_inputActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
        setRutaEntrada(Archivo.rute(this.abs_rute,"Select text","txt"));
    }//GEN-LAST:event_SelectActionPerformed

    public void setRutaEntrada(String ruta){ this.ruta_entrada=ruta; }
    
    public String getRutaEntrada(){ return this.ruta_entrada;}
    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     */
    public static void main(String args[]) throws ClassNotFoundException {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                new Main().setVisible(true);
            });
        } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Hash;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton See_input;
    private javax.swing.JButton See_output;
    private javax.swing.JButton Select;
    private javax.swing.JLabel Select_text;
    private javax.swing.JButton Verify_HASH;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
