/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.Integer.parseInt;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Interfaz extends javax.swing.JFrame {

    private String archivo;
    StringBuilder letra;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.letra=new StringBuilder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelCriptography = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        jLabelIntroduce = new javax.swing.JLabel();
        key_text = new javax.swing.JTextField();
        btnDecrypt = new javax.swing.JButton();
        btnEncrypt = new javax.swing.JButton();
        profa = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnVerSalida = new javax.swing.JButton();
        btnVerEntrada = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Ruiz Hernandez Josue");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 30));

        jLabelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("¡Welcome to my first cryptography program!");
        getContentPane().add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabelCriptography.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabelCriptography.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCriptography.setText("Criptography");
        getContentPane().add(jLabelCriptography, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        btnSelect.setBackground(new java.awt.Color(0, 102, 102));
        btnSelect.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnSelect.setText("Select your file please.");
        btnSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 260, 40));

        jLabelIntroduce.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelIntroduce.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntroduce.setText("Type the key please");
        getContentPane().add(jLabelIntroduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 220, 30));
        getContentPane().add(key_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 90, 30));

        btnDecrypt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnDecrypt.setForeground(new java.awt.Color(255, 255, 255));
        btnDecrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnDecrypt.setText("Decrypt");
        btnDecrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });
        getContentPane().add(btnDecrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 100, 40));

        btnEncrypt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        btnEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnEncrypt.setText("Encrypt");
        btnEncrypt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, 40));

        profa.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        profa.setForeground(new java.awt.Color(255, 255, 255));
        profa.setText("Teacher: Cortéz Duarte Nidia Asunción");
        getContentPane().add(profa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 420, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 100, 40));

        btnVerSalida.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnVerSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnVerSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnVerSalida.setText("See output");
        btnVerSalida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 100, 40));

        btnVerEntrada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnVerEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp3.jpg"))); // NOI18N
        btnVerEntrada.setText("See entry");
        btnVerEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 100, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cp4.jpg"))); // NOI18N
        jLabelFondo.setText(" ");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 466));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        
        int opcion=file.showOpenDialog(this);
        
        if(opcion==JFileChooser.APPROVE_OPTION)
        {
            String nombre=file.getSelectedFile().getPath();
            
            String ruta=file.getSelectedFile().toString();
            
            JOptionPane.showMessageDialog(null,"File successfully loaded");
            
            setArchivo(ruta);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        int llave;
        String cadena;
        llave=parseInt(this.key_text.getText());
        
        if(llave>255)
        {
            llave=llave%255;
        }
        StringBuilder nueva_letra=new StringBuilder();
        
        File fichero= new File(getArchivo());
        
        FileReader f=null;
        try {
            f = new FileReader(fichero);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader b = new BufferedReader(f);
        
        try {
            while((cadena = b.readLine())!=null) {
                char[] aux=cadena.toCharArray();
                for(int i=0;i<aux.length;i++)
                {
                    aux[i]=(char) ((int)aux[i]+llave);
                    nueva_letra.append(aux[i]);
                }
                nueva_letra.append("\r\n");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            b.close();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         try {
            escribirArchivo(nueva_letra);
            JOptionPane.showMessageDialog(null,"You´ve encrypted your message successfully");
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        int llave;
        String cadena;
        llave=parseInt(this.key_text.getText());
        
        if(llave>255)
        {
            llave=llave%256;
        }
        
        StringBuilder nueva_letra=new StringBuilder();
        
        File fichero= new File(getArchivo());
        
        FileReader f=null;
        try {
            f = new FileReader(fichero);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader b = new BufferedReader(f);
        
        try {
            while((cadena = b.readLine())!=null) {
                char[] aux=cadena.toCharArray();
                for(int i=0;i<aux.length;i++)
                {
                    aux[i]=(char) ((int)aux[i]-llave);
                    nueva_letra.append(aux[i]);
                }
                nueva_letra.append("\r\n");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            b.close();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            escribirArchivo(nueva_letra);
            JOptionPane.showMessageDialog(null,"You´ve decrypted your message successfully");
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnVerSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSalidaActionPerformed
        // TODO add your handling code here
        if(getArchivo()!=null)
        {
            String file = "C:\\Users\\josue\\Documents\\Criptography\\Cripto_1\\Salida\\out.txt"; 
   
         try{ 
         //definiendo la ruta en la propiedad file
         Runtime.getRuntime().exec("cmd /c start "+file);
        }catch(IOException e){
        } 
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry, you must encrypt or decrypt a file first at all");
        }
        
    }//GEN-LAST:event_btnVerSalidaActionPerformed

    private void btnVerEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEntradaActionPerformed
        // TODO add your handling code here:
         String file = getArchivo(); 
   
         try{ 
         //definiendo la ruta en la propiedad file
         Runtime.getRuntime().exec("cmd /c start "+file);
        }catch(IOException e){
        } 
    }//GEN-LAST:event_btnVerEntradaActionPerformed

    public void setArchivo(String file)
    {
        this.archivo=file;
    }
    
    public String getArchivo()
    {
        return this.archivo;
    }
    
    public void setLetra(StringBuilder letra)
    {
        this.letra=letra;
    }
    
    public StringBuilder getLetra()
    {
        return this.letra;
    }
    
    public void escribirArchivo(StringBuilder letra) throws IOException
    {
        File out=new File("C:\\Users\\josue\\Documents\\Criptography\\Cripto_1\\Salida\\out.txt");
        
        if(out.delete()){}
        
        File nuevo=new File("C:\\Users\\josue\\Documents\\Criptography\\Cripto_1\\Salida\\out.txt");
        
        try (PrintWriter fw = new PrintWriter(nuevo,"utf-8")) {
            fw.println(letra.toString());
            fw.close();
        }
       System.out.print(letra.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnVerEntrada;
    private javax.swing.JButton btnVerSalida;
    private javax.swing.JLabel jLabelCriptography;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIntroduce;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JTextField key_text;
    private javax.swing.JLabel profa;
    // End of variables declaration//GEN-END:variables
}
