/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rgb;

import java.awt.image.BufferedImage;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */


public class Principal extends javax.swing.JFrame {
    
    Archivo imagen;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        imagen = new Archivo();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selection1 = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Sel = new javax.swing.JLabel();
        Selection = new javax.swing.JButton();
        Entrada = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        R = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        R_A = new javax.swing.JLabel();
        G_A = new javax.swing.JLabel();
        B_A = new javax.swing.JLabel();
        fonfo = new javax.swing.JLabel();

        Selection1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Selection1.setForeground(new java.awt.Color(255, 255, 255));
        Selection1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Selection1.setText("Select");
        Selection1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Josue Ruiz Hernandez");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        Sel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Sel.setForeground(new java.awt.Color(255, 255, 255));
        Sel.setText("Select your image");
        getContentPane().add(Sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        Selection.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Selection.setForeground(new java.awt.Color(255, 255, 255));
        Selection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Selection.setText("Select");
        Selection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectionActionPerformed(evt);
            }
        });
        getContentPane().add(Selection, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 180, 60));

        Entrada.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Entrada.setForeground(new java.awt.Color(255, 255, 255));
        Entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Entrada.setText("See entry");
        Entrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });
        getContentPane().add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 180, 60));

        Salida.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Salida.setForeground(new java.awt.Color(255, 255, 255));
        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Salida.setText("See output");
        Salida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 180, 60));

        Modify.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Modify.setForeground(new java.awt.Color(255, 255, 255));
        Modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Modify.setText("Modify image");
        Modify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });
        getContentPane().add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 60));

        Salir.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fboton.jpg"))); // NOI18N
        Salir.setText("Exit");
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, 60));

        R.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 120, 40));

        G.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 130, 40));

        B.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 140, 40));

        R_A.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        R_A.setForeground(new java.awt.Color(255, 255, 255));
        R_A.setText("R");
        getContentPane().add(R_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        G_A.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        G_A.setForeground(new java.awt.Color(255, 255, 255));
        G_A.setText("G");
        getContentPane().add(G_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        B_A.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        B_A.setForeground(new java.awt.Color(255, 255, 255));
        B_A.setText("B");
        getContentPane().add(B_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        fonfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(fonfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionActionPerformed
       JFileChooser file = new JFileChooser();
        
        int opcion=file.showOpenDialog(this);
        
        if(opcion==JFileChooser.APPROVE_OPTION)
        {
            String nombre=file.getSelectedFile().getPath();
            
            String ruta=file.getSelectedFile().toString();
            
            JOptionPane.showMessageDialog(null,"File successfully loaded");
            
            imagen.setRuta(ruta);
        }
    }//GEN-LAST:event_SelectionActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed
        imagen.mostrarEntrada();
    }//GEN-LAST:event_EntradaActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        imagen.mostrarSalida();
    }//GEN-LAST:event_SalidaActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        String ruta=imagen.getRuta();
        RGB imagen_ = new RGB(ruta,getR(),getG(),getB());
        BufferedImage buffer=null;
        try {
            buffer = imagen_.addImage();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            imagen_.crearImagen(buffer);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"Image modify successfully");
    }//GEN-LAST:event_ModifyActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    public int getR()
    {
        int r = parseInt(this.R.getText());
        return r;
    }
    
    public int getG()
    {
        int r = parseInt(this.G.getText());
        return r;
    }
    
    public int getB()
    {
        int r = parseInt(this.B.getText());
        return r;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B;
    private javax.swing.JLabel B_A;
    private javax.swing.JButton Entrada;
    private javax.swing.JTextField G;
    private javax.swing.JLabel G_A;
    private javax.swing.JButton Modify;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField R;
    private javax.swing.JLabel R_A;
    private javax.swing.JButton Salida;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Sel;
    private javax.swing.JButton Selection;
    private javax.swing.JButton Selection1;
    private javax.swing.JLabel fonfo;
    // End of variables declaration//GEN-END:variables
}
